export const SET_DEBUG_DATA = 'SET_DEBUG_DATA';

export const OPEN_ADD_ACCOUNT_DIALOG = 'OPEN_ADD_ACCOUNT_DIALOG';
export const SELECT_INSTANCE = 'SELECT_INSTANCE';
export const FORWARD_INPUT_DATA_SECTION = 'FORWARD_INPUT_DATA_SECTION';
export const FORWARD_PIN_AUTHORIZATION_SECTION = 'FORWARD_PIN_AUTHORIZATION_SECTION';
export const BACK_SECTION = 'BACK_SECTION';
export const RECEIVE_PIN_ERROR = 'RECEIVE_PIN_ERROR';
export const CLOSE_ADD_ACCOUNT_DIALOG = 'CLOSE_ADD_ACCOUNT_DIALOG';

// General
export const APPLICATION_STARTED = 'APPLICATION_STARTED';
export const REQUEST_LOAD_APPLICATION_DATA = 'REQUEST_LOAD_APPLICATION_DATA';

export const LOAD_ACCOUNT_DATA_SUCCESSED = 'LOAD_ACCOUNT_DATA_SUCCESSED';
export const LOAD_TIMELINE_DATA_SUCCESSED = 'LOAD_TIMELINE_DATA_SUCCESSED';
export const LOAD_DATA_FAILED = 'LOAD_DATA_FAILED';

// Account and auth
export const OPEN_PIN_AUTHORIZATION_WINDOW = 'OPEN_PIN_AUTHORIZATION_WINDOW';
export const REQUEST_PIN_AUTHORIZATION = 'REQUEST_PIN_AUTHORIZATION'; //async
export const PIN_AUTHORIZATION_CANCELED = 'PIN_AUTHORIZATION_CANCELED';

export const AUTHORIZATION_SUCCESSED = 'AUTHORIZATION_SUCCESSED';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const UPDATE_ACCOUNT_DATA = 'UPDATE_ACCOUNT_DATA';

// Timeline
export const ADD_TIMELINE = 'ADD_TIMELINE';
export const DELETE_TIMELINE = 'DELETE_TIMELINE';
export const MOVE_TIMELINE = 'MOVE_TIMELINE';

export const UPDATE_TWEET_BOX = 'UPDATE_TWEET_BOX';
export const POST_TWEET_SUCCESSED = 'POST_TWEET_SUCCESSED';

// Call API
export const REQUEST_GET_API = 'REQUEST_GET_API';
export const TIMELINE_GET_SUCCESSED = 'TIMELINE_GET_SUCCESSED';

export const REQUEST_POST_API = 'REQUEST_POST_API';
export const TIMELINE_POST_SUCCESSED = 'TIMELINE_POST_SUCCESSED';

// snackbars

export const POST_TWEET_FAILED = 'POST_TWEET_FAILED';
export const API_CALL_FAILED = 'API_CALL_FAILED';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const CLOSE_ALL_SNACKBAR = 'CLOSE_ALL_SNACKBAR';
